prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false

  additionalPrometheusRulesMap:
    high-memory-usage:
      groups:
        - name: memory-alerts
          rules:
            - alert: HighMemoryUsage
              expr: (node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100 > 5
              for: 1m
              labels:
                severity: warning
              annotations:
                summary: "High Memory Usage"
                description: "Memory usage is above 5% for more than 1 minutes."
